package ve.techcare.vistas;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import ve.techcare.servicios.utilidades.ConexionBaseDatos;

/**
 *
 * @author Carlos Hernandez
 */
public class AgregarTipo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarTipo
     */
    public AgregarTipo() {
        initComponents();

        this.setLocationRelativeTo(null);
        setIcon();
        fechaFooter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        agregarTipo_txt = new javax.swing.JTextField();
        agregarTipo_lb = new javax.swing.JLabel();
        titulo_lb = new javax.swing.JLabel();
        info_lb3 = new javax.swing.JLabel();
        info_lb = new javax.swing.JLabel();
        info_lb2 = new javax.swing.JLabel();
        acceder_btt = new javax.swing.JButton();
        footer_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(393, 489));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarTipo_txt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        panelFondo.add(agregarTipo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 60));

        agregarTipo_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarTipo_lb.setForeground(new java.awt.Color(0, 0, 0));
        agregarTipo_lb.setText("Agrega el Tipo de equipo aquí");
        panelFondo.add(agregarTipo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Agregar Tipos");
        panelFondo.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 170, 30));

        info_lb3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        info_lb3.setForeground(new java.awt.Color(0, 0, 0));
        info_lb3.setText("movil, ect.");
        panelFondo.add(info_lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 290, -1));

        info_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        info_lb.setForeground(new java.awt.Color(0, 0, 0));
        info_lb.setText("El Tipo se refiere a la forma del equipo  ");
        panelFondo.add(info_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 300, -1));

        info_lb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        info_lb2.setForeground(new java.awt.Color(0, 0, 0));
        info_lb2.setText("y a su funcionalidad, por ejemplo, Laptos,");
        panelFondo.add(info_lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 290, -1));

        acceder_btt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        acceder_btt.setForeground(new java.awt.Color(0, 0, 0));
        acceder_btt.setText("REGISTRAR");
        acceder_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceder_bttActionPerformed(evt);
            }
        });
        panelFondo.add(acceder_btt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, 60));

        footer_lb.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        footer_lb.setForeground(new java.awt.Color(0, 0, 0));
        footer_lb.setText("TechCare® System ");
        panelFondo.add(footer_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceder_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceder_bttActionPerformed
        registrarTipo();
    }//GEN-LAST:event_acceder_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder_btt;
    private javax.swing.JLabel agregarTipo_lb;
    private javax.swing.JTextField agregarTipo_txt;
    private javax.swing.JLabel footer_lb;
    private javax.swing.JLabel info_lb;
    private javax.swing.JLabel info_lb2;
    private javax.swing.JLabel info_lb3;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel titulo_lb;
    // End of variables declaration//GEN-END:variables

    private void fechaFooter() {
        LocalDateTime fechaHora = LocalDateTime.now();
        int year = fechaHora.getYear();
        String fechaFormateada = String.valueOf(year);

        footer_lb.setText("TechCare® System " + fechaFormateada);
    }

    private void setIcon() {
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/imagenes/icono.png"));
            Image scaledImage = originalImage.getScaledInstance(27, 27, Image.SCALE_SMOOTH); // Cambia el tamaño según tus necesidades
            this.setIconImage(scaledImage);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void registrarTipo() {
        String tipo = agregarTipo_txt.getText().trim();

        if (!tipo.isEmpty()) {

            try (Connection con = ConexionBaseDatos.conectar(); PreparedStatement ps = con.prepareStatement("INSERT INTO types(name) VALUES(?)");) {

                ps.setString(1, tipo);

                int respuesta = ps.executeUpdate();

                if (respuesta > 0) {
                    JOptionPane.showMessageDialog(null, "Tipo registrado exitosamente");
                    agregarTipo_lb.setForeground(new Color(0,0,0));
                    agregarTipo_txt.setText("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(AgregarTipo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            agregarTipo_lb.setForeground(new Color(148, 23, 25));
        }
    }
}
