package ve.techcare.vistas;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import ve.techcare.servicios.utilidades.ConexionBaseDatos;

/**
 *
 * @author Carlos Hernandez
 */
public class CambioContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambioContraseña
     */
    private static int id;
    public CambioContraseña() {
        initComponents();
        id= InformacionUsuario.id;
        this.setLocationRelativeTo(null);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_lb = new javax.swing.JLabel();
        confirmaContraseña_lb = new javax.swing.JLabel();
        nuevaContraseña_lb = new javax.swing.JLabel();
        confirmarContraseña_txt = new javax.swing.JTextField();
        nuevaContraseña_txt = new javax.swing.JTextField();
        restablecer_btt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(495, 524));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Cambiar Contraseña");
        jPanel1.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 6, -1, 40));

        confirmaContraseña_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmaContraseña_lb.setForeground(new java.awt.Color(0, 0, 0));
        confirmaContraseña_lb.setText("Confirma la Nueva Contraseña");
        jPanel1.add(confirmaContraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        nuevaContraseña_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuevaContraseña_lb.setForeground(new java.awt.Color(0, 0, 0));
        nuevaContraseña_lb.setText("Nueva Contraseña");
        jPanel1.add(nuevaContraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        confirmarContraseña_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(confirmarContraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 340, 70));

        nuevaContraseña_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(nuevaContraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 340, 70));

        restablecer_btt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        restablecer_btt.setForeground(new java.awt.Color(0, 0, 0));
        restablecer_btt.setText("Restablecer");
        restablecer_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecer_bttActionPerformed(evt);
            }
        });
        jPanel1.add(restablecer_btt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 190, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restablecer_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecer_bttActionPerformed
         restablecerContraseña();
    }//GEN-LAST:event_restablecer_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmaContraseña_lb;
    private javax.swing.JTextField confirmarContraseña_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nuevaContraseña_lb;
    private javax.swing.JTextField nuevaContraseña_txt;
    private javax.swing.JButton restablecer_btt;
    private javax.swing.JLabel titulo_lb;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/imagenes/icono.png"));
            Image scaledImage = originalImage.getScaledInstance(27, 27, Image.SCALE_SMOOTH); // Cambia el tamaño según tus necesidades
            this.setIconImage(scaledImage);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void restablecerContraseña() {
        String nuevaContraseña = nuevaContraseña_txt.getText().trim(),
                confirmarContraseña = confirmarContraseña_txt.getText().trim();

        if (!nuevaContraseña.isEmpty() && !confirmarContraseña.isEmpty()) {
            if (nuevaContraseña.equals(confirmarContraseña)) {

                try (Connection con = ConexionBaseDatos.conectar();
                        PreparedStatement ps= con.prepareStatement("UPDATE users SET password = ? WHERE id = ?");){
                    
                    ps.setString(1, nuevaContraseña);
                    ps.setInt(1, id);
                    
                    int respuesta = ps.executeUpdate();
                    
                    if(respuesta>0){
                        JOptionPane.showMessageDialog(null, "Restablecida Correctamente");
                        this.dispose();
                    }
                    
                } catch (Exception e) {
                      JOptionPane.showMessageDialog(null, "Ocurrio un error al restablecer contraceña, contacte al desarrolladoro");
                }
            } else {
                nuevaContraseña_lb.setForeground(new Color(148, 23, 25));
                confirmaContraseña_lb.setForeground(new Color(148, 23, 25));
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }

        } else {
            nuevaContraseña_lb.setForeground(new Color(148, 23, 25));
            confirmaContraseña_lb.setForeground(new Color(148, 23, 25));
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        }
    }
    
    public CambioContraseña setId(int id){
        this.id= id;
        return this;
    }
}
