
package ve.techcare.vistas;

/**
 *
 * @author Carlos Hernandez
 */
public class CambioContraseña extends javax.swing.JFrame {

    /** Creates new form CambioContraseña */
    public CambioContraseña() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_lb = new javax.swing.JLabel();
        confirmaContraseña_lb = new javax.swing.JLabel();
        nuevaContraseña_lb = new javax.swing.JLabel();
        confirmarContraseña_txt = new javax.swing.JTextField();
        nuevaContraseña_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(495, 524));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Cambiar Contraseña");
        jPanel1.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 6, -1, 40));

        confirmaContraseña_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmaContraseña_lb.setForeground(new java.awt.Color(0, 0, 0));
        confirmaContraseña_lb.setText("Confirma la Nueva Contraseña");
        jPanel1.add(confirmaContraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        nuevaContraseña_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuevaContraseña_lb.setForeground(new java.awt.Color(0, 0, 0));
        nuevaContraseña_lb.setText("Nueva Contraseña");
        jPanel1.add(nuevaContraseña_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        confirmarContraseña_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(confirmarContraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 340, 70));

        nuevaContraseña_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(nuevaContraseña_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 340, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmaContraseña_lb;
    private javax.swing.JTextField confirmarContraseña_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nuevaContraseña_lb;
    private javax.swing.JTextField nuevaContraseña_txt;
    private javax.swing.JLabel titulo_lb;
    // End of variables declaration//GEN-END:variables

}
