package ve.techcare.vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import ve.techcare.servicios.utilidades.ConexionBaseDatos;

/**
 *
 * @author Carlos Hernandez
 */
public class GraficaEstatus extends javax.swing.JFrame {

    /**
     * Creates new form GraficaEstatus
     */
    public GraficaEstatus() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        graficarEstatus();
        fechaFooter();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        titulo_lb = new javax.swing.JLabel();
        footer_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1040, 665));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Grafica de los Equipos según su Estatus");
        panelFondo.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 460, 40));

        footer_lb.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        footer_lb.setForeground(new java.awt.Color(0, 0, 0));
        footer_lb.setText("TechCare® System ");
        panelFondo.add(footer_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaEstatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaEstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer_lb;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel titulo_lb;
    // End of variables declaration//GEN-END:variables

    private void graficarEstatus() {

        // OBTENCION DEL CONTEO DE LOS ESTATUS DESDE LA BASE DE DATOS.
        int nuevoIngreso = 0, enRevision = 0, reparado = 0, noReparado = 0, entregado = 0;

        try (Connection con = ConexionBaseDatos.conectar(); PreparedStatement ps = con.prepareStatement(
                "SELECT status, COUNT(*) AS cantidad FROM equipments GROUP BY status"); ResultSet rs = ps.executeQuery();) {

            while (rs.next()) {
                String estatus = rs.getString("status");
                int cantidad = rs.getInt("cantidad");

                switch (estatus) {
                    case "Nuevo Ingreso":
                        nuevoIngreso = cantidad;

                        break;
                    case "En Revision":
                        enRevision = cantidad;
                        break;
                    case "Reparado":
                        reparado = cantidad;
                        break;
                    case "No Reparado":
                        noReparado = cantidad;
                        break;
                    case "Entregado":
                        entregado = cantidad;
                        break;
                    default:
                        break;

                }

            }

            System.out.println("Nuevo Ingreso: " + nuevoIngreso + " En Revision: " + enRevision + " Reparado: " + reparado);
            System.out.println("No Reparado: " + noReparado + " Entregado: " + entregado);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener el conteo de los estatus para graficar.");
            System.out.println("Error en Obtener Cantidades de equipos segun su estatus");
            System.out.println(e);
        }
        // CREACION DEL GRAFICO DE BARRAS
        DefaultCategoryDataset datosGraficos = new DefaultCategoryDataset();

        // Establecer los datos traidos desde la base de datos al data set
        datosGraficos.setValue(nuevoIngreso, "Nuevo Ingreso", "Nuevo Ingreso");
        datosGraficos.setValue(enRevision, "En Revision", "En Revision");
        datosGraficos.setValue(reparado, "Reparado", "Reparado");
        datosGraficos.setValue(noReparado, "No Reparado", "No Reparado");
        datosGraficos.setValue(entregado, "Entregado", "Entregado");

        JFreeChart grafico = ChartFactory.createBarChart(
                "Grafica de Estatus",
                "Valores",
                "Cantidades",
                datosGraficos);

        BarRenderer renderer = (BarRenderer) grafico.getCategoryPlot()
                .getRenderer();

        renderer.setShadowVisible(false);
        renderer.setBarPainter(new StandardBarPainter());
        renderer.setItemMargin(-1.5);
        renderer.setMaximumBarWidth(1.0);

        grafico.getPlot().setBackgroundPaint(Color.WHITE);
        grafico.getCategoryPlot().setRangeGridlinePaint(new Color(150, 150, 150));
        grafico.getCategoryPlot().setDomainGridlinePaint(new Color(150, 150, 150));

        NumberAxis rangeAxis = (NumberAxis) grafico.getCategoryPlot().getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        ChartPanel panel = new ChartPanel(grafico);
        panel.setPreferredSize(new Dimension(980, 520));

        panelFondo.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, 980, 520));
        panelFondo.revalidate();
        panelFondo.repaint();

    }

    private void fechaFooter() {
        LocalDateTime fechaHora = LocalDateTime.now();
        int year = fechaHora.getYear();
        String fechaFormateada = String.valueOf(year);

        footer_lb.setText("TechCare® System " + fechaFormateada);
    }

    private void setIcon() {
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/imagenes/icono.png"));
            Image scaledImage = originalImage.getScaledInstance(27, 27, Image.SCALE_SMOOTH); // Cambia el tamaño según tus necesidades
            this.setIconImage(scaledImage);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
