package ve.techcare.vistas;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import ve.techcare.servicios.utilidades.ConexionBaseDatos;

/**
 *
 * @author Carlos Hernandez
 */
public class InformacionUsuario extends javax.swing.JFrame {

    public static int id;

    public InformacionUsuario() {
        initComponents();
        registradoPor_txt.setEditable(false);
        this.setLocationRelativeTo(null);
        id= GestionUsuarios.id;
        setIcon();
        fechaFooter();
        traerInfoUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        titulo_lb = new javax.swing.JLabel();
        footer_lb = new javax.swing.JLabel();
        nombreCompleto_lb = new javax.swing.JLabel();
        dni_lb = new javax.swing.JLabel();
        correo_lb = new javax.swing.JLabel();
        telefono_lb = new javax.swing.JLabel();
        nombreUsuario_lb = new javax.swing.JLabel();
        roles_lb = new javax.swing.JLabel();
        registradoPor_lb = new javax.swing.JLabel();
        estatus_lb = new javax.swing.JLabel();
        nombreCompleto_txt = new javax.swing.JTextField();
        dni_txt = new javax.swing.JTextField();
        correo_txt = new javax.swing.JTextField();
        telefono_txt = new javax.swing.JTextField();
        registradoPor_txt = new javax.swing.JTextField();
        nombreUsuario_txt = new javax.swing.JTextField();
        roles_cbx = new javax.swing.JComboBox<>();
        estatus_cbx = new javax.swing.JComboBox<>();
        actualizar_btt = new javax.swing.JButton();
        cambiarContraseña_btt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1040, 665));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Informacion del Usuario");
        panelFondo.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 280, 40));

        footer_lb.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        footer_lb.setForeground(new java.awt.Color(0, 0, 0));
        footer_lb.setText("TechCare® System ");
        panelFondo.add(footer_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 240, 20));

        nombreCompleto_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreCompleto_lb.setForeground(new java.awt.Color(0, 0, 0));
        nombreCompleto_lb.setText("Nombre Completo");
        panelFondo.add(nombreCompleto_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        dni_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dni_lb.setForeground(new java.awt.Color(0, 0, 0));
        dni_lb.setText("DNI (Cedula, Identificacion Nacional)");
        panelFondo.add(dni_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        correo_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo_lb.setForeground(new java.awt.Color(0, 0, 0));
        correo_lb.setText("Correo Electronico");
        panelFondo.add(correo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        telefono_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telefono_lb.setForeground(new java.awt.Color(0, 0, 0));
        telefono_lb.setText("Número de Telefono");
        panelFondo.add(telefono_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        nombreUsuario_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreUsuario_lb.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuario_lb.setText("Nombre de Usuario");
        panelFondo.add(nombreUsuario_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        roles_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roles_lb.setForeground(new java.awt.Color(0, 0, 0));
        roles_lb.setText("Roles");
        panelFondo.add(roles_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        registradoPor_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registradoPor_lb.setForeground(new java.awt.Color(0, 0, 0));
        registradoPor_lb.setText("Registrado / modificado por");
        panelFondo.add(registradoPor_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        estatus_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estatus_lb.setForeground(new java.awt.Color(0, 0, 0));
        estatus_lb.setText("Estatus");
        panelFondo.add(estatus_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));

        nombreCompleto_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(nombreCompleto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 370, 60));

        dni_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(dni_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 370, 60));

        correo_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(correo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 370, 60));

        telefono_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(telefono_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 370, 60));

        registradoPor_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(registradoPor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 370, 60));

        nombreUsuario_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(nombreUsuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 370, 60));

        roles_cbx.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        roles_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Administrador", "Capturista", "Tecnico" }));
        panelFondo.add(roles_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 370, 60));

        estatus_cbx.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        estatus_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Activo", "Inactivo" }));
        panelFondo.add(estatus_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 370, 60));

        actualizar_btt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        actualizar_btt.setForeground(new java.awt.Color(0, 0, 0));
        actualizar_btt.setText("ACTUALIZAR");
        actualizar_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_bttActionPerformed(evt);
            }
        });
        panelFondo.add(actualizar_btt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 170, 70));

        cambiarContraseña_btt.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        cambiarContraseña_btt.setForeground(new java.awt.Color(0, 0, 0));
        cambiarContraseña_btt.setText("CAMBIAR CONTRASEÑA");
        cambiarContraseña_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseña_bttActionPerformed(evt);
            }
        });
        panelFondo.add(cambiarContraseña_btt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 170, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizar_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_bttActionPerformed
        actualizarUsuario();
    }//GEN-LAST:event_actualizar_bttActionPerformed

    private void cambiarContraseña_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseña_bttActionPerformed
        new CambioContraseña().setVisible(true);
    }//GEN-LAST:event_cambiarContraseña_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_btt;
    private javax.swing.JButton cambiarContraseña_btt;
    private javax.swing.JLabel correo_lb;
    private javax.swing.JTextField correo_txt;
    private javax.swing.JLabel dni_lb;
    private javax.swing.JTextField dni_txt;
    private javax.swing.JComboBox<String> estatus_cbx;
    private javax.swing.JLabel estatus_lb;
    private javax.swing.JLabel footer_lb;
    private javax.swing.JLabel nombreCompleto_lb;
    private javax.swing.JTextField nombreCompleto_txt;
    private javax.swing.JLabel nombreUsuario_lb;
    private javax.swing.JTextField nombreUsuario_txt;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel registradoPor_lb;
    private javax.swing.JTextField registradoPor_txt;
    private javax.swing.JComboBox<String> roles_cbx;
    private javax.swing.JLabel roles_lb;
    private javax.swing.JLabel telefono_lb;
    private javax.swing.JTextField telefono_txt;
    private javax.swing.JLabel titulo_lb;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource("/imagenes/icono.png"));
            Image scaledImage = originalImage.getScaledInstance(27, 27, Image.SCALE_SMOOTH); // Cambia el tamaño según tus necesidades
            this.setIconImage(scaledImage);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void fechaFooter() {
        LocalDateTime fechaHora = LocalDateTime.now();
        int year = fechaHora.getYear();
        String fechaFormateada = String.valueOf(year);

        footer_lb.setText("TechCare® System " + fechaFormateada);
    }

    private void traerInfoUsuario() {

        String nombreCompleto = "", dni = "", correo = "", telefono = "", usuario = "", rol = "", estatus = "", registradoPor = "";

        try (Connection con = ConexionBaseDatos.conectar(); PreparedStatement ps = con.prepareStatement(
                "SELECT full_name, dni, email, phone, username, role, status, registered_by FROM "
                + "users WHERE id = ?");) {

            ps.setInt(1, id);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                nombreCompleto = rs.getString("full_name");
                dni = rs.getString("dni");
                correo = rs.getString("email");
                telefono = rs.getString("phone");
                usuario = rs.getString("username");
                rol = rs.getString("role");
                estatus = rs.getString("status");
                registradoPor = rs.getString("registered_by");
            }

            nombreCompleto_txt.setText(nombreCompleto);
            dni_txt.setText(dni);
            correo_txt.setText(correo);
            telefono_txt.setText(telefono);
            registradoPor_txt.setText(registradoPor);
            nombreUsuario_txt.setText(usuario);
            roles_cbx.setSelectedItem(getRoles(rol));
            estatus_cbx.setSelectedIndex(getEstatusIndex(estatus));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al Traer Info del usuario(InformacionUsuario), contacte al desarrollador");
        }
    }
    
    private void actualizarUsuario(){
        String nombreCompleto = nombreCompleto_txt.getText().trim(),
                dni = dni_txt.getText().trim(),
                correo = correo_txt.getText().trim(),
                telefono = telefono_txt.getText().trim(), 
                usuario = nombreUsuario_txt.getText().trim(),
                rol = getRoles(roles_cbx),
                estatus = getEstatus(estatus_cbx);
        
        if(!nombreCompleto.isEmpty() && !dni.isEmpty() && !correo.isEmpty() && !telefono.isEmpty() 
                && !usuario.isEmpty() && !rol.equals("Selecciona") && !estatus.equals("Selecciona")){
            
            try (Connection con = ConexionBaseDatos.conectar();
                 PreparedStatement ps = con.prepareStatement(
         "UPDATE users SET full_name = ?, dni = ?, email = ?, phone = ?, username = ?, role = ?, status = ? WHERE id =?");){
                
                ps.setString(1, nombreCompleto);
                ps.setString(2,dni );
                ps.setString(3,correo);
                ps.setString(4, telefono);
                ps.setString(5, usuario);
                ps.setString(6,rol);
                ps.setString(7,estatus);
                ps.setInt(8,id);
                
                int respuesta = ps.executeUpdate();
                
                if(respuesta >0){
                    JOptionPane.showMessageDialog(null, "Usuario actualizado con exito");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al Actualizar usuario(InformacionUsuario), contacte al desarrollador");
            }
        }else{
            nombreCompleto_lb.setForeground(new Color(148, 23, 25));
            dni_lb.setForeground(new Color(148, 23, 25));
            correo_lb.setForeground(new Color(148, 23, 25));
            telefono_lb.setForeground(new Color(148, 23, 25));
            nombreUsuario_lb.setForeground(new Color(148, 23, 25));
            roles_lb.setForeground(new Color(148, 23, 25));
            estatus_lb.setForeground(new Color(148, 23, 25));
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos requeridos");
        }
                
    }

    private String getRoles(String roles) {

        if (roles.equals("admin")) {
            return "Administrador";

        } else if (roles.equals("captu")) {
            return "Capturista";

        } else if (roles.equals("tec")) {
            return "Tecnico";

        } else {
            return roles;
        }

    }

    private int getEstatusIndex(String estatus) {

        switch (estatus) {
            case "activo" -> {
                return 1;
            }

            case "inactivo" -> {
                return 2;
            }
            default -> {
                return 0;
            }
        }
    }

    private String getEstatus(JComboBox<String> statusBox) {
        int estatus = statusBox.getSelectedIndex();

        switch (estatus) {
            case 1 -> {
                return "activo";
            }
            case 2 -> {
                return "inactivo";
            }

            default -> {
                return "Selecciona";
            }

        }
    }

    private String getRoles(JComboBox<String> rolesBox) {
        String roles = (String) rolesBox.getSelectedItem();

        if (roles.equals("Administrador")) {
            return "admin";

        } else if (roles.equals("Capturista")) {
            return "captu";

        } else if (roles.equals("Tecnico")) {
            return "tec";

        } else {
            return roles;
        }

    }
}
