
package ve.techcare.vistas;

/**
 *
 * @author Carlos Hernandez
 */
public class InformacionEquipo extends javax.swing.JFrame {

    /** Creates new form InformacionEquipo */
    public InformacionEquipo() {
        initComponents();
        cliente_txt.setEditable(false);
        ultimoModificar_txt.setEditable(false);
        fechaIngreso_txt.setEditable(false);
        ultimaModification_txt.setEditable(false);
        dañosReportados_txa.setLineWrap(true);
        comentariosTecnicos_txa.setLineWrap(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        titulo_lb = new javax.swing.JLabel();
        footer_lb = new javax.swing.JLabel();
        cliente_lb = new javax.swing.JLabel();
        cliente_txt = new javax.swing.JTextField();
        marcas_cbx = new javax.swing.JComboBox<>();
        marca_lb = new javax.swing.JLabel();
        tipoEquipos_cbx = new javax.swing.JComboBox<>();
        tipoEquipos_lb = new javax.swing.JLabel();
        modelo_lb = new javax.swing.JLabel();
        modelo_txt = new javax.swing.JTextField();
        numeroSerie_lb = new javax.swing.JLabel();
        numeroSerie_txt = new javax.swing.JTextField();
        ultimoModificar_lb = new javax.swing.JLabel();
        ultimoModificar_txt = new javax.swing.JTextField();
        fechaIngreso_lb = new javax.swing.JLabel();
        fechaIngreso_txt = new javax.swing.JTextField();
        ultimaModificacion_lb = new javax.swing.JLabel();
        ultimaModification_txt = new javax.swing.JTextField();
        estatus_lb = new javax.swing.JLabel();
        estatus_cbx = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentariosTecnicos_txa = new javax.swing.JTextArea();
        dañosReportados_lb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dañosReportados_txa = new javax.swing.JTextArea();
        comentariosTecnicos_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1040, 665));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_lb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo_lb.setForeground(new java.awt.Color(0, 0, 0));
        titulo_lb.setText("Informacion del Equipo");
        panelFondo.add(titulo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 280, 40));

        footer_lb.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        footer_lb.setForeground(new java.awt.Color(0, 0, 0));
        footer_lb.setText("TechCare® System ");
        panelFondo.add(footer_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 240, 20));

        cliente_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cliente_lb.setForeground(new java.awt.Color(0, 0, 0));
        cliente_lb.setText("Cliente");
        panelFondo.add(cliente_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        cliente_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 370, 60));

        marcas_cbx.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        marcas_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        panelFondo.add(marcas_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 370, 60));

        marca_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        marca_lb.setForeground(new java.awt.Color(0, 0, 0));
        marca_lb.setText("Marcas");
        panelFondo.add(marca_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        tipoEquipos_cbx.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tipoEquipos_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        panelFondo.add(tipoEquipos_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 370, 60));

        tipoEquipos_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoEquipos_lb.setForeground(new java.awt.Color(0, 0, 0));
        tipoEquipos_lb.setText("Tipo de Equipos");
        panelFondo.add(tipoEquipos_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        modelo_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modelo_lb.setForeground(new java.awt.Color(0, 0, 0));
        modelo_lb.setText("Modelo");
        panelFondo.add(modelo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        modelo_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(modelo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 370, 60));

        numeroSerie_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numeroSerie_lb.setForeground(new java.awt.Color(0, 0, 0));
        numeroSerie_lb.setText("Numero de Serie");
        panelFondo.add(numeroSerie_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        numeroSerie_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(numeroSerie_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 370, 60));

        ultimoModificar_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ultimoModificar_lb.setForeground(new java.awt.Color(0, 0, 0));
        ultimoModificar_lb.setText("Ultimo en modificar");
        panelFondo.add(ultimoModificar_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        ultimoModificar_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(ultimoModificar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 370, 60));

        fechaIngreso_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fechaIngreso_lb.setForeground(new java.awt.Color(0, 0, 0));
        fechaIngreso_lb.setText("Fecha de Ingreso");
        panelFondo.add(fechaIngreso_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        fechaIngreso_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(fechaIngreso_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 370, 40));

        ultimaModificacion_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ultimaModificacion_lb.setForeground(new java.awt.Color(0, 0, 0));
        ultimaModificacion_lb.setText("Ultima Modificacion");
        panelFondo.add(ultimaModificacion_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        ultimaModification_txt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        panelFondo.add(ultimaModification_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 370, 40));

        estatus_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estatus_lb.setForeground(new java.awt.Color(0, 0, 0));
        estatus_lb.setText("Estatus");
        panelFondo.add(estatus_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        estatus_cbx.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        estatus_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Nuevo Ingreso", "En Revision", "Reparado", "No Reparado", "Entregado" }));
        panelFondo.add(estatus_cbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 370, 40));

        comentariosTecnicos_txa.setColumns(20);
        comentariosTecnicos_txa.setRows(5);
        jScrollPane1.setViewportView(comentariosTecnicos_txa);

        panelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 370, 110));

        dañosReportados_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dañosReportados_lb.setForeground(new java.awt.Color(0, 0, 0));
        dañosReportados_lb.setText("Daños Reportados");
        panelFondo.add(dañosReportados_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        dañosReportados_txa.setEditable(false);
        dañosReportados_txa.setColumns(20);
        dañosReportados_txa.setRows(5);
        jScrollPane2.setViewportView(dañosReportados_txa);

        panelFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 370, 100));

        comentariosTecnicos_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comentariosTecnicos_lb.setForeground(new java.awt.Color(0, 0, 0));
        comentariosTecnicos_lb.setText("Comentarios Tecnicos");
        panelFondo.add(comentariosTecnicos_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cliente_lb;
    private javax.swing.JTextField cliente_txt;
    private javax.swing.JLabel comentariosTecnicos_lb;
    private javax.swing.JTextArea comentariosTecnicos_txa;
    private javax.swing.JLabel dañosReportados_lb;
    private javax.swing.JTextArea dañosReportados_txa;
    private javax.swing.JComboBox<String> estatus_cbx;
    private javax.swing.JLabel estatus_lb;
    private javax.swing.JLabel fechaIngreso_lb;
    private javax.swing.JTextField fechaIngreso_txt;
    private javax.swing.JLabel footer_lb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel marca_lb;
    private javax.swing.JComboBox<String> marcas_cbx;
    private javax.swing.JLabel modelo_lb;
    private javax.swing.JTextField modelo_txt;
    private javax.swing.JLabel numeroSerie_lb;
    private javax.swing.JTextField numeroSerie_txt;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JComboBox<String> tipoEquipos_cbx;
    private javax.swing.JLabel tipoEquipos_lb;
    private javax.swing.JLabel titulo_lb;
    private javax.swing.JLabel ultimaModificacion_lb;
    private javax.swing.JTextField ultimaModification_txt;
    private javax.swing.JLabel ultimoModificar_lb;
    private javax.swing.JTextField ultimoModificar_txt;
    // End of variables declaration//GEN-END:variables

}
